Name:           ros-jade-slam-gmapping
Version:        1.3.8
Release:        0%{?dist}
Summary:        ROS slam_gmapping package

Group:          Development/Libraries
License:        CreativeCommons-by-nc-sa-2.0
URL:            http://ros.org/wiki/slam_gmapping
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-jade-gmapping
Requires:       ros-jade-openslam-gmapping
BuildRequires:  ros-jade-catkin

%description
slam_gmapping contains a wrapper around gmapping which provides SLAM
capabilities.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Fri Jul 31 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 1.3.8-0
- Autogenerated by Bloom

* Sat Jul 04 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 1.3.7-0
- Autogenerated by Bloom

* Wed Feb 11 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 1.3.5-0
- Autogenerated by Bloom

